language: go

go:
  - 1.8.x
  - 1.7.x
  - 1.6.x
  - 1.5.x
#  - 1.4.3 # https://github.com/cavaliercoder/grab/issues/7

install: make test-deps

script: make check

env: 
  - GOARCH=amd64
  - GOARCH=386
